<?php

/**
 * @file
 * Contains functionalities and hook for this module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\field\FieldStorageConfigInterface;

/**
 * Implements hook_field_views_data_alter().
 */
function views_taxonomy_radios_filter_field_views_data_alter(array &$data, FieldStorageConfigInterface $field_storage) {
  if ($field_storage->getType() == 'entity_reference' && $field_storage->getSetting('target_type') == 'taxonomy_term') {
    foreach ($data as $table_name => $table_data) {
      foreach ($table_data as $field_name => $field_data) {
        if (isset($field_data['filter']) && $field_name != 'delta') {
          $data[$table_name][$field_name]['filter']['id'] = 'taxonomy_index_tid_radios';
        }
      }
    }
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function views_taxonomy_radios_filter_form_views_exposed_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Alter default '<Any>' or '- Any -' choices to display 'All' as it makes more
  // sense in the context of a radios/checkboxes element.
  foreach (Element::children($form) as $key) {
    if (($all_label = $form[$key]['#all_label'] ?? NULL) && ($form[$key]['#options']['All'] ?? NULL)) {
      $form[$key]['#options']['All'] = t($all_label);
    }
  }
}
